name: Python application

on:
  push:
    branches: [ "automated" ]
  pull_request:
    branches: [ "automated" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    services:
      selenium:
        image: selenium/standalone-chrome
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.8.10"
    - name: Prepare Selenium
      # https://github.com/marketplace/actions/setup-chromedriver
    - uses: nanasess/setup-chromedriver@master
    - name: Launch browser
    - name: Start XVFB
      run: |
        google-chrome --version
        export DISPLAY=:99
        chromedriver --url-base=/wd/hub &
        sudo Xvfb -ac :99 -screen 0 1280x1024x24 > /dev/null 2>&1 & # optional, disables headless mode   
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        python -m pytest tip_paid.py
      env:
        DISPLAY: :99
