name: Test

on: [push, workflow_dispatch]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm install --no-save @testmo/testmo-cli
      - run: |
          npx testmo automation:run:submit \
            --instance https://qlub.testmo.net \
            --project-id 2 \
            --name "GitHub-Action" \
            --source "test" \
            --results results/*.xml

      - name: Secret Token
        with: # Set the secret as an input
          super_secret: ${{ secrets.TESTMO_URL }}
        env: # Or as an environment variable
          super_secret: ${{ secrets.TESTMO_TOKEN }}
