name: Test

on: [push, workflow_dispatch]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
      - run: npm install --no-save @testmo/testmo-cli
      - run: |
          npx testmo automation:run:submit \
            --instance https://qlub.testmo.net \
            --project-id 2 \
            --name "GitHub-Action" \
            --source "test" \
            --results results/*.xml \
        env:
          TESTMO_URL: https://qlub.testmo.net
          TESTMO_TOKEN: testmo_api_eyJpdiI6Ik5XLzZiWG42ZXZsTlhCVld6QTBSZVE9PSIsInZhbHVlIjoiNmt0Z3BTODlPalJCcG15MW4xMnRobDhwa3E1TlZvNWE1UHdTQTBOOXJFST0iLCJtYWMiOiI1MTdiZGU1Zjc5OTUxNDEyZDQxYWFmNGMzNmFjYjhmNGE0NzlmZmM4MjFiZWU5NTdhMjEzYzExZTgyNjc5OGJmIiwidGFnIjoiIn0=
