name: Test

on: [push, workflow_dispatch]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v3
        with:
          python-version: 3.8.10
      - run: python3 install --no-save @testmo/testmo-cli
      - run: |
          npx testmo automation:run:submit \
            --instance $TESTMO_URL \
            --project-id 2 \
            --name "Selenium with Pytest" \
            --source "customer-app" \
            --results /home/sasan/Documents/Python/results/* \
            -- python3 run pytest # Note space after --
        env:
          TESTMO_URL: ${{ secrets.TESTMO_URL }}
          TESTMO_TOKEN: ${{ secrets.TESTMO_TOKEN }}
